In [1]:
# Create two random vectors, one to store the goals (from zero to 20) and
# another one to store the assistances (from 0 to 10)
import numpy as np

names = ["Roberto Firminho", "Harry Kane", "Lionel Messi", "Luis Diaz", "Lorenzo Insigne"]
nationalities = ["Brazil", "England", "Argentina", "Colombia", "Italia"]
goals_vect = np.random.randint(0, 15, size=(5, ))
assistance_vect = np.random.randint(0, 20, size=(5, ))

print(goals_vect)
print(assistance_vect)

[11 11  3  6  5]
[ 2  3  7  2 12]


In [2]:
my_list = ["Jose garcia", "Carolina Martinez"]
my_vector = np.array([my_list])
names_column = my_vector.T
print(names_column)

[['Jose garcia']
 ['Carolina Martinez']]


In [3]:
my_cities_list = ["Medellin", "Bucaramanga"]
my_cities_vector = np.array([my_cities_list])
my_cities_column = my_cities_vector.T
print(my_cities_column)

[['Medellin']
 ['Bucaramanga']]


In [4]:
result = np.concatenate([names_column, my_cities_column], axis=1)
print(result)

[['Jose garcia' 'Medellin']
 ['Carolina Martinez' 'Bucaramanga']]


In [5]:
# Create the names and nationalities columns from the names and nationalities lists
# value using the vector's transpose
names_column = np.array([names]).T
nationalities_column = np.array([nationalities]).T

#print(names_column)
#print(nationalities_column)

# Concatenate the columns to create an unique matrix
data_matrix = np.concatenate([names_column, nationalities_column], axis=1)
print(data_matrix)

[['Roberto Firminho' 'Brazil']
 ['Harry Kane' 'England']
 ['Lionel Messi' 'Argentina']
 ['Luis Diaz' 'Colombia']
 ['Lorenzo Insigne' 'Italia']]


In [6]:
# Create the goals and assistances columns from the names and nationalities lists
# value using the vector's transpose
goals_column = np.array([goals_vect]).T
assistance_column = np.array([assistance_vect]).T


# Concatenate the columns to create an unique matrix
#data_matrix = np.concatenate([names_column, nationalities_column, goals_column, assistance_column], axis=1)
data_matrix = np.concatenate([data_matrix, goals_column, assistance_column], axis=1)
print(data_matrix)

[['Roberto Firminho' 'Brazil' '11' '2']
 ['Harry Kane' 'England' '11' '3']
 ['Lionel Messi' 'Argentina' '3' '7']
 ['Luis Diaz' 'Colombia' '6' '2']
 ['Lorenzo Insigne' 'Italia' '5' '12']]


In [7]:
test_matrix = np.array([
                        ["jose", 20, 30, "garcia"],
                        ["carolina", 30, 50, "perez"],
                        ["jesus", 40, 60, "perez"],
                        ["antonio", 10, 80, "hincapie"],
])
result = test_matrix[:, [1, 2]]
print(result)

[['20' '30']
 ['30' '50']
 ['40' '60']
 ['10' '80']]


In [8]:
# Create a new matrix that contains only the columns of goals and assistances

work_data = data_matrix[:, [2, 3]]
print(work_data)

# Cast the matrix to store only int values
work_data = np.array(work_data, dtype=np.int64)
print(work_data)

[['11' '2']
 ['11' '3']
 ['3' '7']
 ['6' '2']
 ['5' '12']]
[[11  2]
 [11  3]
 [ 3  7]
 [ 6  2]
 [ 5 12]]


In [15]:
matrix = np.array([
    [3, 4, 5, 6],
    [30, 40, 1, 2],
    [27, 7, 50, 90],
]
)
result_without_axis = np.amax(matrix)
print(matrix)
print(result_without_axis)

result_with_axis_0 = np.amax(matrix, axis=0)
print(f"result with axis=0: {result_with_axis_0}")

result_with_axis_1 = np.amax(matrix, axis=1)
print(f"result with axis=1: {result_with_axis_1}")

[[ 3  4  5  6]
 [30 40  1  2]
 [27  7 50 90]]
90
result with axis=0: [30 40 50 90]
result with axis=1: [ 6 40 90]


In [17]:
# find the best scorer and assistant

max_values = np.amax(work_data, axis=0)
print(max_values)

highest_score = max_values[0]
highest_assistance = max_values[1]

print(f"max score value: {highest_score}")
print(f"max assistance value: {highest_assistance}")

[11 12]
max score value: 11
max assistance value: 12


In [18]:
print(data_matrix)

[['Roberto Firminho' 'Brazil' '11' '2']
 ['Harry Kane' 'England' '11' '3']
 ['Lionel Messi' 'Argentina' '3' '7']
 ['Luis Diaz' 'Colombia' '6' '2']
 ['Lorenzo Insigne' 'Italia' '5' '12']]


In [35]:
print(data_matrix[3, :])

['Luis Diaz' 'Colombia' '6' '2']


In [42]:
import math, copy
import datetime

names_column = data_matrix[:, [0]]
print(names_column)

names_vector = names_column.flatten()
print(names_vector)

messi_position = np.where(names_vector == "Lionel Messi")
print(messi_position)
print(messi_position[0][0])

messi_information = data_matrix[2, :]
print(messi_information)

[['Roberto Firminho']
 ['Harry Kane']
 ['Lionel Messi']
 ['Luis Diaz']
 ['Lorenzo Insigne']]
['Roberto Firminho' 'Harry Kane' 'Lionel Messi' 'Luis Diaz'
 'Lorenzo Insigne']
(array([2]),)
2
['Lionel Messi' 'Argentina' '3' '7']


In [49]:
print(data_matrix)
print(work_data)

[['Roberto Firminho' 'Brazil' '11' '2']
 ['Harry Kane' 'England' '11' '3']
 ['Lionel Messi' 'Argentina' '3' '7']
 ['Luis Diaz' 'Colombia' '6' '2']
 ['Lorenzo Insigne' 'Italia' '5' '12']]
[[11  2]
 [11  3]
 [ 3  7]
 [ 6  2]
 [ 5 12]]


In [50]:
# find the position of the best assistance

assistance_column = work_data[:, [1]]
print(assistance_column)

assistance_vector = assistance_column.flatten()
best_assistant_positions = np.where(assistance_vector == highest_assistance)
print(best_assistant_positions)

[[ 2]
 [ 3]
 [ 7]
 [ 2]
 [12]]
(array([4]),)


In [53]:
print(work_data)

[[11  2]
 [11  3]
 [ 3  7]
 [ 6  2]
 [ 5 12]]


In [52]:
# find the position of the best forwarder

scores_column = work_data[:, [0]]

scores_vector = scores_column.flatten()
best_forwader_positions = np.where(scores_vector == highest_score)
print(best_forwader_positions)

(array([0, 1]),)


In [ ]:
# Let's remember the data matrix

print(data_matrix)

In [67]:
my_tuple = (1, 4, "jose", 5, True)
print(my_tuple)

my_tuple_2 = ("jose",)
print(my_tuple_2[0])

my_array = np.array([1, 2, 3])
print(my_array[2])

for item in my_array:
    print(item)

my_array_2 = np.array([10])
print(my_array_2[0])

print("----")
for item in my_array_2:
    print(item)


(1, 4, 'jose', 5, True)
jose
3
1
2
3
10
----
10


In [75]:
print(data_matrix)
print("---")
print(data_matrix[4, 0])

[['Roberto Firminho' 'Brazil' '11' '2']
 ['Harry Kane' 'England' '11' '3']
 ['Lionel Messi' 'Argentina' '3' '7']
 ['Luis Diaz' 'Colombia' '6' '2']
 ['Lorenzo Insigne' 'Italia' '5' '12']]
---
Lorenzo Insigne


In [81]:
# Now, print the names of the best assistants

print("the best assistants are:")
assitance_positions = best_assistant_positions[0]
print(best_assistant_positions)
#print(best_assistant_positions)
#print(assitance_positions)

for position in assitance_positions:
    name = data_matrix[position, 0]
    print(name)

the best assistants are:
(array([4]),)
Lorenzo Insigne


In [80]:
# Now, print the names of the best forwarders

print("the best forwarders are:")
positions = best_forwader_positions[0]
print(best_forwader_positions)
for position in positions:
    name = data_matrix[position, 0]
    print(name)

the best forwarders are:
(array([0, 1]),)
Roberto Firminho
Harry Kane
