In [19]:
# Create two random vectors, one to store the goals (from zero to 20) and
# another one to store the assistances (from 0 to 10)
import numpy as np

names = ["Roberto Firminho", "Harry Kane", "Lionel Messi", "Luis Diaz", "Lorenzo Insigne"]
nationalities = ["Brazil", "England", "Argentina", "Colombia", "Italia"]
goals_vect = np.random.randint(0, 15, size=(5, ))
assistance_vect = np.random.randint(0, 20, size=(5, ))

print(goals_vect)
print(assistance_vect)

[13  0  8  5  9]
[ 4 15 13 16  8]


In [9]:
my_list = ["Jose garcia", "Carolina Martinez"]
my_vector = np.array([my_list])
names_column = my_vector.T
print(names_column)

[['Jose garcia']
 ['Carolina Martinez']]


In [20]:
my_cities_list = ["Medellin", "Bucaramanga"]
my_cities_vector = np.array([my_cities_list])
my_cities_column = my_cities_vector.T
print(my_cities_column)

[['Medellin']
 ['Bucaramanga']]


In [18]:
result = np.concatenate([names_column, my_cities_column], axis=1)
print(result)

[['Jose garcia' 'Medellin']
 ['Carolina Martinez' 'Bucaramanga']]


In [23]:
# Create the names and nationalities columns from the names and nationalities lists
# value using the vector's transpose
names_column = np.array([names]).T
nationalities_column = np.array([nationalities]).T

#print(names_column)
#print(nationalities_column)

# Concatenate the columns to create an unique matrix
data_matrix = np.concatenate([names_column, nationalities_column], axis=1)
print(data_matrix)

[['Roberto Firminho' 'Brazil']
 ['Harry Kane' 'England']
 ['Lionel Messi' 'Argentina']
 ['Luis Diaz' 'Colombia']
 ['Lorenzo Insigne' 'Italia']]


In [28]:
# Create the goals and assistances columns from the names and nationalities lists
# value using the vector's transpose
goals_column = np.array([goals_vect]).T
assistance_column = np.array([assistance_vect]).T


# Concatenate the columns to create an unique matrix
#data_matrix = np.concatenate([names_column, nationalities_column, goals_column, assistance_column], axis=1)
data_matrix = np.concatenate([data_matrix, goals_column, assistance_column], axis=1)
print(data_matrix)

[['Roberto Firminho' 'Brazil' '13' '4']
 ['Harry Kane' 'England' '0' '15']
 ['Lionel Messi' 'Argentina' '8' '13']
 ['Luis Diaz' 'Colombia' '5' '16']
 ['Lorenzo Insigne' 'Italia' '9' '8']]


In [34]:
test_matrix = np.array([
                        ["jose", 20, 30, "garcia"],
                        ["carolina", 30, 50, "perez"],
                        ["jesus", 40, 60, "perez"],
                        ["antonio", 10, 80, "hincapie"],
])
result = test_matrix[:, [1, 2]]
print(result)

[['20' '30']
 ['30' '50']
 ['40' '60']
 ['10' '80']]


In [35]:
# Create a new matrix that contains only the columns of goals and assistances

work_data = data_matrix[:, [2, 3]]
print(work_data)

# Cast the matrix to store only int values
work_data = np.array(work_data, dtype=np.int64)
print(work_data)

[['13' '4']
 ['0' '15']
 ['8' '13']
 ['5' '16']
 ['9' '8']]
[[13  4]
 [ 0 15]
 [ 8 13]
 [ 5 16]
 [ 9  8]]


In [ ]:
# find the best scorer and assistant

max_values = ____
print(max_values)

highest_scorer = ___
highest_assistance = ___

In [ ]:
# find the position of the best assistance

assistance_column = ___

assistance_vector = assistance_column.flatten()
best_assistant_positions = ___
print(best_assistant_positions)

In [ ]:
# find the position of the best forwarder

scores_column = ___

scores_vector = scores_column.flatten()
best_forwader_positions = ___
print(best_forwader_positions)

In [ ]:
# Let's remember the data matrix

print(data_matrix)

In [ ]:
# Now, print the names of the best assistants

print("the best assistants are:")
positions = best_assistant_positions[0]
for position in positions:
    print(___)

In [ ]:
# Now, print the names of the best assistants

print("the best forwarders are:")
positions = best_forwader_positions[0]
for position in positions:
    print(___)